

services:
  frontend:
    build:
      context: ./frontend/my-app  # Path to your frontend Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./  # Root folder is the context for backend (ensure it includes requirements.txt)
      dockerfile: ./backend/Dockerfile  # Specify the backend Dockerfile location
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
      - DATABASE_URL=mysql+mysqlconnector://root@localhost:3306/user_database
    depends_on:
      - mysql
    networks:
      - app-network

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: user_database
    ports:
      - "3307:3307"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local
