# Use an official Python runtime as a parent image
FROM python:3.10-slim

# Set the working directory in the container
WORKDIR /app/backend

# Copy the requirements.txt from the root to /app in the container
COPY requirements.txt /app/

# Copy the backend files into the container
COPY ./backend /app/backend

# Install dependencies
RUN pip install --no-cache-dir -r /app/requirements.txt

RUN pip install mysql-connector-python

# Expose the port the Flask app will run on
EXPOSE 5001

# Set Flask environment variables
ENV FLASK_APP=app
ENV FLASK_ENV=production

# Command to run the Flask app
CMD ["python", "-m", "flask", "run", "--host=0.0.0.0", "--port=5001"]
