name: Lambda Deployment Pipeline

on:
  push:
    branches:
      - cognito-auth
  workflow_dispatch:

jobs:
  deploy-to-S3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Zip Functions and Deploy
        run: |
          mkdir -p dist
          for lambda_file in ./serverless/*.py; do
            function_name=$(basename $lambda_file .py)
            zip -j dist/$function_name.zip $lambda_file
            aws s3 cp dist/$function_name.zip s3://${{ vars.AWS_LAMBDA_BUCKET }}
          done
